# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/nuket/Eigendoxx
  rev: main
  hooks:
  - id: gps-metadata-check
  - id: gps-metadata-remove
